$mainMod = SUPER
$files = thunar
$term = kitty
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

#bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window # Super Key to Launch rofi menu
bind = $mainMod, D, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window #Main Menu

bind = $mainMod CTRL, F, fullscreen, 1 # fake full screen

# ags overview
bind = $mainMod, A, exec, pkill rofi || true && ags -t 'overview'

bind = $mainMod, Return, exec, $term -e tmux  #terminal
bind = $mainMod, T, exec, $files #file manager

bind = $mainMod ALT, C, exec, $UserScripts/RofiCalc.sh # calculator (qalculate)

# pyprland
bind = $mainMod SHIFT, Return, exec, pypr toggle term # Dropdown terminal
bind = $mainMod, Z, exec, pypr zoom # Toggle Desktop Zoom

# User Added Keybinds
bind = $mainMod SHIFT, O, exec, $UserScripts/ZshChangeTheme.sh # Change oh-my-zsh theme
bindn = ALT_L SHIFT_L, Q, exec, $scriptsDir/SwitchKeyboardLayout.sh # Change keyboard layout
bind = Alt SHIFT, B, exec, brave
bind = Alt SHIFT, S, exec, spotify
bind = Alt SHIFT,O, exec, obs
bind = ,F4, pass, class:^(com\.obsproject\.Studio)$
bind = Alt SHIFT, D, exec, discord
bind = Alt SHIFT, D, exec, vesktop
bind = Alt SHIFT, C, exec, chromium
bind=$mainMod SHIFT,Q, exec, zsh -c 'tmux kill-server'
