# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000004)
$foreground = rgb(E6E5E0)
$color0 = rgb(000004)
$color1 = rgb(545556)
$color2 = rgb(655D5C)
$color3 = rgb(655D5C)
$color4 = rgb(848279)
$color5 = rgb(87857C)
$color6 = rgb(8A887E)
$color7 = rgb(D3D1CB)
$color8 = rgb(94938E)
$color9 = rgb(707173)
$color10 = rgb(867B7A)
$color11 = rgb(867B7A)
$color12 = rgb(B0ADA2)
$color13 = rgb(B5B1A5)
$color14 = rgb(B8B5A8)
$color15 = rgb(D3D1CB)
