# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EFEDE9
background         #111111
cursor             #EFEDE9

active_tab_foreground     #111111
active_tab_background     #EFEDE9
inactive_tab_foreground   #EFEDE9
inactive_tab_background   #111111

active_border_color   #EFEDE9
inactive_border_color #111111
bell_border_color     #0D0D0D

color0      #393939
color1		#0D0D0D
color2		#161615
color3		#43423E
color4		#6A634E
color5		#706D67
color6		#9D9990
color7		#DFDDD7
color8		#9C9B97
color9		#111111
color10		#1D1D1C
color11		#595753
color12		#8D8468
color13		#95928A
color14		#D1CDC0
color15		#DFDDD7
