# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(111111)
$foreground = rgb(EFEDE9)
$color0 = rgb(393939)
$color1 = rgb(0D0D0D)
$color2 = rgb(161615)
$color3 = rgb(43423E)
$color4 = rgb(6A634E)
$color5 = rgb(706D67)
$color6 = rgb(9D9990)
$color7 = rgb(DFDDD7)
$color8 = rgb(9C9B97)
$color9 = rgb(111111)
$color10 = rgb(1D1D1C)
$color11 = rgb(595753)
$color12 = rgb(8D8468)
$color13 = rgb(95928A)
$color14 = rgb(D1CDC0)
$color15 = rgb(DFDDD7)
